exp_name: "late_fusion_RGB7"

task: "segmentation"
data_root: "MM5_SEG"
modalities: ["rgb", "depth"]
rgb_folder: "RGB7"
img_size: [224, 224]

model_type: "late_fusion"
pretrained: true

batch_size: 16
epochs: 200
learning_rate: 0.001
weight_decay: 0.0001
num_workers: 4

save_dir: "experiments/late_fusion_RGB7"
save_freq: 1000
