exp_name: "early_fusion_RGB2"

task: "segmentation"
data_root: "MM5_SEG"
modalities: ["rgb", "depth"]
rgb_folder: "RGB2"
img_size: [224, 224]

model_type: "early_fusion"
pretrained: true

batch_size: 16
epochs: 300
learning_rate: 0.001
weight_decay: 0.0001
num_workers: 4

save_dir: "experiments/early_fusion_RGB2"
save_freq: 1000
