exp_name: "rgb_baseline_RGB3"

task: "segmentation"
data_root: "MM5_SEG"
modalities: ["rgb", "depth"]
rgb_folder: "RGB3"
img_size: [224, 224]

model_type: "rgb_baseline"
pretrained: true

batch_size: 32
epochs: 300
learning_rate: 0.001
weight_decay: 0.0001
num_workers: 4

save_dir: "experiments/rgb_baseline_RGB3"
save_freq: 1000
