# ResNet U-Net Mid Fusion (RGB + Depth fused after encoder)
exp_name: "mid_fusion"

task: "segmentation"
data_root: "MM5_SEG"
modalities: ["rgb", "depth"]
img_size: [224, 224]

model_type: "mid_fusion"
pretrained: true

batch_size: 16
num_workers: 4
epochs: 200
learning_rate: 0.001
weight_decay: 0.0001

save_dir: "experiments/mid_fusion_3"
save_freq: 1000
