# ResNet U-Net RGB-only baseline for segmentation
exp_name: "rgb_baseline"

# Task
task: "segmentation" 

# Data
data_root: "MM5_SEG"
train_split: "train"
eval_split: "eval"
modalities: ["rgb"]
img_size: [224, 224]

# Model
model_type: "rgb"  # 'unet_rgb', 'unet_early_fusion', 'unet_mid_fusion'
pretrained: true

# Training
batch_size: 16
num_workers: 4
epochs: 200
learning_rate: 0.001
weight_decay: 0.0001

# Saving
save_dir: "experiments/rgb_baseline_3"
save_freq: 1000